server:
  port: 7501
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=iot&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
springdoc:
  show-actuator: true
  model-and-view-allowed: true
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  packagesToScan: com.jackmouse.system.blog


queue:
  type: kafka
  transport_api:
    requests_topic: jm_transport.api.requests
    responses_topic: jm_transport.api.responses
    max_pending_requests: 10000
    max_requests_timeout: 1000000
    max_callback_threads: 100
    request_poll_interval: 25
    response_poll_interval: 25
    max_core_handler_threads: 16
  kafka:
    bootstrap-servers: localhost:9092
#    ssl-enabled: false
#    ssl-truststore-location: classpath:truststore.jks
#    ssl-truststore-password: 12345678
#    ssl-keystore-location: classpath:keystore.jks
#    ssl-keystore-password: 12345678
#    ssl-key-password: 12345678
    acks: all
    compression-type: none
    batch-size: 16384
    linger-ms: 1
    max-request-size: 1048576
    max-in-flight-requests-per-connection: 5
    buffer-memory: 33554432
    replication-factor: 1
    max-poll-records: 8192
    max-partition-fetch-bytes: 16777216
    max-poll-interval-ms: 300000
    fetch-max-bytes: 134217728
    request-timeout-ms: 30000
    session-timeout-ms: 10000
    auto-offset-reset: earliest
    use-confluent: false
    retries: 1
    topic-properties:
      transport-api: "${TB_QUEUE_KAFKA_TA_TOPIC_PROPERTIES:retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000;partitions:10;min.insync.replicas:1}"

#    ssl-algorithm: 1
#    sasl-mechanism: PLAIN
#    security-protocol: PLAINTEXT
#    other-inline: ""


transport:
  http:
    request_timeout: 60000
    max_request_timeout: 300000

service:
  type: monolith
  id: "${JM_SERVICE_ID:}"