server:
  port: 7501
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=iot&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
springdoc:
  show-actuator: true
  model-and-view-allowed: true
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  packagesToScan: com.jackmouse.system.blog

queue:
  transport_api:
    requests_topic: jm_transport.api.requests
    responses_topic: jm_transport.api.responses
    max_pending_requests: 10000
    max_requests_timeout: 10000
    max_callback_threads: 100
    request_poll_interval: 25
    response_poll_interval: 25

transport:
  http:
    request_timeout: 60000
    max_request_timeout: 300000

service:
  id: "${JM_SERVICE_ID:}"